package com.example.airnavigate.Model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NEWS".
 */
public class News {

    private long id;
    private String image2Fullscreen;
    private String currentPage;
    private String subtitle;
    private String author;
    private String videoUrl;
    private String title;
    private int index;
    private String text;
    private String image;
    private int totalPages;
    private String teaser;
    private String url;
    private boolean featured;
    private String contentType;
    private java.util.Date date;
    private String image2;
    private String imageFullscreen;
    private String twitterScreenName;
    private String twitterAtName;
    private String twitterLogo;
    private String twitterRetweetAtName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public News() {
    }

    public News(long id) {
        this.id = id;
    }

    public News(long id, String image2Fullscreen, String currentPage, String subtitle, String author, String videoUrl, String title, int index, String text, String image, int totalPages, String teaser, String url, boolean featured, String contentType, java.util.Date date, String image2, String imageFullscreen, String twitterScreenName, String twitterAtName, String twitterLogo, String twitterRetweetAtName) {
        this.id = id;
        this.image2Fullscreen = image2Fullscreen;
        this.currentPage = currentPage;
        this.subtitle = subtitle;
        this.author = author;
        this.videoUrl = videoUrl;
        this.title = title;
        this.index = index;
        this.text = text;
        this.image = image;
        this.totalPages = totalPages;
        this.teaser = teaser;
        this.url = url;
        this.featured = featured;
        this.contentType = contentType;
        this.date = date;
        this.image2 = image2;
        this.imageFullscreen = imageFullscreen;
        this.twitterScreenName = twitterScreenName;
        this.twitterAtName = twitterAtName;
        this.twitterLogo = twitterLogo;
        this.twitterRetweetAtName = twitterRetweetAtName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getImage2Fullscreen() {
        return image2Fullscreen;
    }

    public void setImage2Fullscreen(String image2Fullscreen) {
        this.image2Fullscreen = image2Fullscreen;
    }

    public String getCurrentPage() {
        return currentPage;
    }

    public void setCurrentPage(String currentPage) {
        this.currentPage = currentPage;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public int getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(int totalPages) {
        this.totalPages = totalPages;
    }

    public String getTeaser() {
        return teaser;
    }

    public void setTeaser(String teaser) {
        this.teaser = teaser;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public boolean getFeatured() {
        return featured;
    }

    public void setFeatured(boolean featured) {
        this.featured = featured;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getImage2() {
        return image2;
    }

    public void setImage2(String image2) {
        this.image2 = image2;
    }

    public String getImageFullscreen() {
        return imageFullscreen;
    }

    public void setImageFullscreen(String imageFullscreen) {
        this.imageFullscreen = imageFullscreen;
    }

    public String getTwitterScreenName() {
        return twitterScreenName;
    }

    public void setTwitterScreenName(String twitterScreenName) {
        this.twitterScreenName = twitterScreenName;
    }

    public String getTwitterAtName() {
        return twitterAtName;
    }

    public void setTwitterAtName(String twitterAtName) {
        this.twitterAtName = twitterAtName;
    }

    public String getTwitterLogo() {
        return twitterLogo;
    }

    public void setTwitterLogo(String twitterLogo) {
        this.twitterLogo = twitterLogo;
    }

    public String getTwitterRetweetAtName() {
        return twitterRetweetAtName;
    }

    public void setTwitterRetweetAtName(String twitterRetweetAtName) {
        this.twitterRetweetAtName = twitterRetweetAtName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
