package com.example.airnavigate.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.airnavigate.Dao.Topic;
import com.example.airnavigate.Dao.Deputy;
import com.example.airnavigate.Dao.Education;
import com.example.airnavigate.Dao.Activity;

import com.example.airnavigate.Dao.TopicDao;
import com.example.airnavigate.Dao.DeputyDao;
import com.example.airnavigate.Dao.EducationDao;
import com.example.airnavigate.Dao.ActivityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topicDaoConfig;
    private final DaoConfig deputyDaoConfig;
    private final DaoConfig educationDaoConfig;
    private final DaoConfig activityDaoConfig;

    private final TopicDao topicDao;
    private final DeputyDao deputyDao;
    private final EducationDao educationDao;
    private final ActivityDao activityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topicDaoConfig = daoConfigMap.get(TopicDao.class).clone();
        topicDaoConfig.initIdentityScope(type);

        deputyDaoConfig = daoConfigMap.get(DeputyDao.class).clone();
        deputyDaoConfig.initIdentityScope(type);

        educationDaoConfig = daoConfigMap.get(EducationDao.class).clone();
        educationDaoConfig.initIdentityScope(type);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        topicDao = new TopicDao(topicDaoConfig, this);
        deputyDao = new DeputyDao(deputyDaoConfig, this);
        educationDao = new EducationDao(educationDaoConfig, this);
        activityDao = new ActivityDao(activityDaoConfig, this);

        registerDao(Topic.class, topicDao);
        registerDao(Deputy.class, deputyDao);
        registerDao(Education.class, educationDao);
        registerDao(Activity.class, activityDao);
    }
    
    public void clear() {
        topicDaoConfig.getIdentityScope().clear();
        deputyDaoConfig.getIdentityScope().clear();
        educationDaoConfig.getIdentityScope().clear();
        activityDaoConfig.getIdentityScope().clear();
    }

    public TopicDao getTopicDao() {
        return topicDao;
    }

    public DeputyDao getDeputyDao() {
        return deputyDao;
    }

    public EducationDao getEducationDao() {
        return educationDao;
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

}
