package com.example.airnavigate.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.airnavigate.Dao.Topic;
import com.example.airnavigate.Dao.Deputy;
import com.example.airnavigate.Dao.VotingResult;
import com.example.airnavigate.Dao.Voting;

import com.example.airnavigate.Dao.TopicDao;
import com.example.airnavigate.Dao.DeputyDao;
import com.example.airnavigate.Dao.VotingResultDao;
import com.example.airnavigate.Dao.VotingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topicDaoConfig;
    private final DaoConfig deputyDaoConfig;
    private final DaoConfig votingResultDaoConfig;
    private final DaoConfig votingDaoConfig;

    private final TopicDao topicDao;
    private final DeputyDao deputyDao;
    private final VotingResultDao votingResultDao;
    private final VotingDao votingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topicDaoConfig = daoConfigMap.get(TopicDao.class).clone();
        topicDaoConfig.initIdentityScope(type);

        deputyDaoConfig = daoConfigMap.get(DeputyDao.class).clone();
        deputyDaoConfig.initIdentityScope(type);

        votingResultDaoConfig = daoConfigMap.get(VotingResultDao.class).clone();
        votingResultDaoConfig.initIdentityScope(type);

        votingDaoConfig = daoConfigMap.get(VotingDao.class).clone();
        votingDaoConfig.initIdentityScope(type);

        topicDao = new TopicDao(topicDaoConfig, this);
        deputyDao = new DeputyDao(deputyDaoConfig, this);
        votingResultDao = new VotingResultDao(votingResultDaoConfig, this);
        votingDao = new VotingDao(votingDaoConfig, this);

        registerDao(Topic.class, topicDao);
        registerDao(Deputy.class, deputyDao);
        registerDao(VotingResult.class, votingResultDao);
        registerDao(Voting.class, votingDao);
    }
    
    public void clear() {
        topicDaoConfig.getIdentityScope().clear();
        deputyDaoConfig.getIdentityScope().clear();
        votingResultDaoConfig.getIdentityScope().clear();
        votingDaoConfig.getIdentityScope().clear();
    }

    public TopicDao getTopicDao() {
        return topicDao;
    }

    public DeputyDao getDeputyDao() {
        return deputyDao;
    }

    public VotingResultDao getVotingResultDao() {
        return votingResultDao;
    }

    public VotingDao getVotingDao() {
        return votingDao;
    }

}
