package com.example.airnavigate.Dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.airnavigate.Dao.Education;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EDUCATIONS".
*/
public class EducationDao extends AbstractDao<Education, Void> {

    public static final String TABLENAME = "EDUCATIONS";

    /**
     * Properties of entity Education.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Institution = new Property(0, String.class, "institution", false, "INSTITUTION");
        public final static Property Year = new Property(1, String.class, "year", false, "YEAR");
        public final static Property EducationId = new Property(2, long.class, "educationId", false, "EDUCATION_ID");
    };

    private DaoSession daoSession;


    public EducationDao(DaoConfig config) {
        super(config);
    }
    
    public EducationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EDUCATIONS\" (" + //
                "\"INSTITUTION\" TEXT," + // 0: institution
                "\"YEAR\" TEXT," + // 1: year
                "\"EDUCATION_ID\" INTEGER NOT NULL );"); // 2: educationId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EDUCATIONS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Education entity) {
        stmt.clearBindings();
 
        String institution = entity.getInstitution();
        if (institution != null) {
            stmt.bindString(1, institution);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(2, year);
        }
        stmt.bindLong(3, entity.getEducationId());
    }

    @Override
    protected void attachEntity(Education entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Education readEntity(Cursor cursor, int offset) {
        Education entity = new Education( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // institution
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // year
            cursor.getLong(offset + 2) // educationId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Education entity, int offset) {
        entity.setInstitution(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setYear(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEducationId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Education entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Education entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDeputyDao().getAllColumns());
            builder.append(" FROM EDUCATIONS T");
            builder.append(" LEFT JOIN DEPUTY T0 ON T.\"EDUCATION_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Education loadCurrentDeep(Cursor cursor, boolean lock) {
        Education entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Deputy deputy = loadCurrentOther(daoSession.getDeputyDao(), cursor, offset);
         if(deputy != null) {
            entity.setDeputy(deputy);
        }

        return entity;    
    }

    public Education loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Education> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Education> list = new ArrayList<Education>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Education> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Education> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
