package com.example.airnavigate.Dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TOPIC".
 */
public class Topic {

    private long id;
    private String name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Topic() {
    }

    public Topic(long id) {
        this.id = id;
    }

    public Topic(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
